apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: default # Defines the namespace explicitly
spec:
  type: LoadBalancer # Exposes the service externally
  selector:
    app: spring-boot-app # Selects the pods from the Deployment above
  ports:
    - name: http
      port: 80 # External port for the Load Balancer
      targetPort: 8080 # Internal port of the Spring Boot application container
      protocol: TCP
